#!/bin/bash

../gradlew makehookmethodJar

if [ ! -d build/outputs/libs ]; then
    mkdir -p build/outputs/libs
fi

cp -a build/intermediates/library_and_local_jars_jni/release/arm* build/outputs/libs
cp -a build/outputs/libs/* ../app/libs/

 
